### ISSUE TITLE
Issue in your backtrack function

### ISSUE THREAD

**Issue by HodayaAt** [speix/8-puzzle#1]
Hi :)
I try to run your code, in the basic example (like in your readMe) - it's work.
But in more complex example that required to use at backtrack, the flow failed.
This is the example and error message:

**python driver.py bfs 0,8,7,2,5,4,3,6,1**
Traceback (most recent call last):
  File "driver.py", line 362, in <module>
    main()
  File "driver.py", line 351, in main
    export(frontier, stop-start)
  File "driver.py", line 304, in export
    moves = backtrace()
  File "driver.py", line 283, in backtrace
    while initial_state != current_node.state:
AttributeError: class State has no attribute 'state'

I try to solve it, but I didn't understand the error.

I glad if you can help me :)
Best regards!
Hodaya

**Comment by Vaiorello** [comment]
Hello, after many hours, I found out why it is not working.You see, not all puzzles are solvable, the problem is when you try to force a not solvable to work.Let's take for example bfs. You have this line of code: `explored, queue = set(), deque([State(start_state, None, None, 0, 0, 0)])`
After that you enter in a while where you do `deque.popleft()` .Instead of going into the if statement where returns queue, you run out of items in your queue and exit the while statement.

To fix this issue you need to check you board before you continue, here is the function:
`def checkSolvable(array):
    numberOfInversions = 0

    for i in range(0, len(array)):
        for j in range(i+1, len(array)):
            if(array[j] > array[i]):
                numberOfInversions += 1

    if numberOfInversions % 2 == 1:
        return False
    else:
        return True`
